<?php

$action = $_GET['action'] ?? '/';

match ($action) {
    '/'         => (new HomeController)->index(),
    'admin'     => (new AdminController)->index(),
    'login'     => (new AuthController)->login(),
    'logout'    => (new AuthController)->logout(),
    'partner'   => (new PartnerController)->dashboard(),
    'partner-logs' => (new PartnerController)->logs(),
    'tour-categories'  => (new TourCategoryController)->index(),
    'tours'             => (new TourController)->index(),

    'tour-categories-create'  => (new TourCategoryController)->create(),
    'tour-categories-store'   => (new TourCategoryController)->store(),
    'tour-categories-edit'    => (new TourCategoryController)->edit(),
    'tour-categories-update'  => (new TourCategoryController)->update(),
    'tour-categories-delete'  => (new TourCategoryController)->delete(),
    'tours-detail'       => (new TourController)->detail(),
    'tours-itinerary-create' => (new TourController)->createItinerary(), // Hiển thị form
    'tours-itinerary-store'  => (new TourController)->storeItinerary(),
    'tours-itinerary-edit'   => (new TourController)->editItinerary(),
    'tours-itinerary-update' => (new TourController)->updateItinerary(),
    'tours-itinerary-delete' => (new TourController)->deleteItinerary(),
    
    'tours-create'  => (new TourController)->create(),
    'tours-store'   => (new TourController)->store(),
    'tours-edit'    => (new TourController)->edit(),
    'tours-update'  => (new TourController)->update(),
    'tours-delete'  => (new TourController)->delete(),
    'tours-get-info' => (new TourController)->getTourInfo(),
    'tours-itinerary-json' => (new TourController)->getItineraryJson(),

    // Nhật ký tour: trang quản trị xem/lọc, HDV ghi chép
    'tour-logs-list'   => (new TourController)->logsList(),
    'tour-logs-store'  => (new TourController)->logsStore(),
    'tour-logs-update' => (new TourController)->logsUpdate(),
    'tour-logs-delete' => (new TourController)->logsDelete(),

    'bookings'              => (new BookingController)->index(),
    'bookings-create'        => (new BookingController)->create(),
    'bookings-store'         => (new BookingController)->store(),
    'bookings-edit'          => (new BookingController)->edit(),
    'bookings-update'        => (new BookingController)->update(),
    'bookings-update-status' => (new BookingController)->updateStatus(),
    'bookings-delete'        => (new BookingController)->delete(),

    'customers'         => (new CustomerController)->index(),
    'customers-create'  => (new CustomerController)->create(),
    'customers-edit'    => (new CustomerController)->edit(),
    'customers-store'   => (new CustomerController)->store(),
    'customers-update'  => (new CustomerController)->update(),
    'customers-delete'  => (new CustomerController)->delete(),

    'guides'         => (new GuideController)->index(),
    'guides-create'  => (new GuideController)->create(),
    'guides-store'   => (new GuideController)->store(),
    'guides-edit'    => (new GuideController)->edit(),
    'guides-update'  => (new GuideController)->update(),
    'guides-update-status' => (new GuideController)->updateStatus(),
    'guides-delete'  => (new GuideController)->delete(),

    'users'          => (new UserController)->index(),
    'users-create'   => (new UserController)->create(),
    'users-edit'    => (new UserController)->edit(),
    'users-update'  => (new UserController)->update(),
    'users-store'   => (new UserController)->store(),
    'users-delete'  => (new UserController)->delete(),
    'assignments'        => (new AssignmentController)->index(),
    'assignments-create' => (new AssignmentController)->create(),
    'assignments-store'  => (new AssignmentController)->store(),
    'assignments-edit'   => (new AssignmentController)->edit(),
    'assignments-update' => (new AssignmentController)->update(),
    'assignments-delete' => (new AssignmentController)->delete(),
    'services'           => (new ServiceController)->index(),
    'services-create'    => (new ServiceController)->create(),
    'services-store'     => (new ServiceController)->store(),
    'services-edit'      => (new ServiceController)->edit(),
    'services-update'    => (new ServiceController)->update(),
    'services-delete'    => (new ServiceController)->delete(),

    'tour-management'        => (new TourManagementController)->index(),
    'tour-group-create'      => (new TourManagementController)->createGroup(),
    'tour-group-store'       => (new TourManagementController)->storeGroup(),
    'tour-group-update-status'=> (new TourManagementController)->updateGroupStatus(),
    'tour-group-delete'      => (new TourManagementController)->deleteGroup(),
    'tour-guests'            => (new TourManagementController)->listGuests(),
    'tour-guest-add'         => (new TourManagementController)->addGuest(),
    'tour-guest-store'       => (new TourManagementController)->storeGuest(),
    'tour-guest-edit'        => (new TourManagementController)->editGuest(),
    'tour-guest-update'      => (new TourManagementController)->updateGuest(),
    'tour-guest-checkin'     => (new TourManagementController)->checkinGuest(),
    'tour-guest-assign-room' => (new TourManagementController)->assignRoom(),
    'tour-guest-delete'      => (new TourManagementController)->deleteGuest(),
    'tour-guests-print'      => (new TourManagementController)->printList(),
};
